//Future: automatically pull these constants
export const subjectMap = {
    ACCT: "Accounting",
    AFAM: "African American Studies",
    AMST: "American Studies",
    ANTH: "Anthropology",
    ARAB: "Arabic",
    ART: "Art",
    ARTE: "Art Education",
    ASAM: "Asian American Studies",
    ASTR: "Astronomy",
    BIOL: "Biological Science",
    BUAD: "Business Administration",
    CHEM: "Chemistry and Biochemistry",
    CHIC: "Chicana and Chicano Studies",
    CAS: "Child and Adolescent Studies",
    CHIN: "Chinese",
    CTVA: "Cinema and Television Arts",
    EGCE: "Civil & Environmental Engr",
    CNSM: "Coll of Natural Sci & Math",
    COMD: "Comm Sciences and Disorders",
    COMM: "Communications",
    CPLT: "Comparative Literature",
    EGCP: "Computer Engineering",
    CPSC: "Computer Science",
    COUN: "Counseling",
    CRED: "Credential Studies",
    CRJU: "Criminal Justice",
    DANC: "Dance",
    SBAE: "EXED Business & Econ",
    SEDU: "EXED Education",
    SECS: "EXED Engineer & Comp Sci",
    SHSS: "EXED Humanities/Soc Sci",
    ECON: "Economics",
    EDD: "Education Leadership Doctorate",
    EDAD: "Educational Leadership",
    EGEE: "Electrical Engineering",
    EDEL: "Elementary & Bilingual Ed",
    ENGL: "English",
    ENED: "English Education",
    ENST: "Environmental Studies",
    EUST: "European Studies",
    EXED: "Extended Education",
    XINT: "Extension International Stds",
    FIN: "Finance",
    FREN: "French",
    EGGN: "General Engineering",
    GEOG: "Geography and the Environment",
    GEOL: "Geological Sciences",
    GRMN: "German",
    GERO: "Gerontology",
    GRAD: "Graduate Studies",
    HESC: "Health Science",
    HIST: "History",
    HONR: "Honors",
    HCOM: "Human Communication Studies",
    HUSR: "Human Services",
    HUM: "Humanities",
    ISDS: "Info Systems & Decision Sci",
    IDT: "Instructional Design & Tech",
    INST: "International Studies",
    ITAL: "Italian",
    JAPN: "Japanese",
    KNES: "Kinesiology",
    KORE: "Korean",
    LTAM: "Latin American Studies",
    LBST: "Liberal Studies",
    LING: "Linguistics",
    MGMT: "Management",
    MKTG: "Marketing",
    MSW: "Master of Social Work",
    MAED: "Math Education",
    MATH: "Mathematics",
    EGME: "Mechanical Engineering",
    MLSC: "Military Science",
    MLNG: "Modern Languages & Literatures",
    MUS: "Music",
    MUSE: "Music Education",
    NURS: "Nursing",
    PERS: "Persian",
    PHIL: "Philosophy",
    PHYS: "Physics",
    POSC: "Political Science",
    PORT: "Portuguese",
    PSYC: "Psychology",
    READ: "Reading",
    REG: "Registrar",
    RLST: "Religious Studies",
    SCED: "Science Education",
    EDSC: "Secondary Education",
    SOCI: "Sociology",
    SPAN: "Spanish",
    SPED: "Special Education",
    TESL: "Teach English Spkrs Oth Lang",
    THTR: "Theatre",
    THED: "Theatre Education",
    UNIV: "University Studies",
    VIET: "Vietnamese",
    WGST: "Women & Gender Studies"
};
